PLAYING = 0
CHECKMATE_BY_WHITE = 1
CHECKMATE_BY_BLACK = 2
STALEMATE = 3
INSUFFICIENT_MATERIAL = 4
TIME_PASSED_WHITE = 5
TIME_PASSED_BLACK = 6


GAME_PAUSED = 7

TIME_1_MUNUTES = 60
TIME_5_MINUTES = 5 * 60
TIME_10_MINUTES = 10 * 60

MOVES_TO_GO_DEFAULT = 60
MOVES_TO_GO_BLITZ = 80