FPS = 60

SCREEN_WIDTH = 900 # Extra space for UI elements
SCREEN_HEIGHT = SCREEN_WIDTH

BOARD_WIDTH = SCREEN_WIDTH - 300 # Leave space for UI elements
BOARD_HEIGHT = BOARD_WIDTH
SQUARE_SIZE = BOARD_WIDTH // 8
GAP_SQAURE =  SQUARE_SIZE * 0.05 # Gap between squares

BOARD_X = (SCREEN_WIDTH - BOARD_WIDTH) // 2 
BOARD_Y = (SCREEN_HEIGHT - BOARD_HEIGHT) // 2

PIECE_SIZE = int(SQUARE_SIZE * 0.9)  # Leave some padding around pieces


TURN_INDICATOR_RADIUS = 15
GAP_TURN_INDICATOR = 5
TURN_INDICATOR_X = BOARD_X + BOARD_WIDTH + TURN_INDICATOR_RADIUS + GAP_TURN_INDICATOR
TURN_INDICATOR_Y = BOARD_Y + TURN_INDICATOR_RADIUS

GAP_PROMOTION_TABLE = BOARD_HEIGHT // 15
PROMOTION_TABLE_Y = BOARD_Y + BOARD_HEIGHT + GAP_PROMOTION_TABLE
PROMOTION_TABLE_WIDTH = BOARD_WIDTH * 0.35
PROMOTION_TABLE_CELL_WIDTH = PROMOTION_TABLE_WIDTH // 4
PROMOTION_TABLE_CELL_HEIGHT = PROMOTION_TABLE_CELL_WIDTH
PROMOTION_TABLE_X = BOARD_X + (BOARD_WIDTH - PROMOTION_TABLE_WIDTH) // 2