# screen
FPS = 60

SCREEN_WIDTH = 1400 # Extra space for UI elements
SCREEN_HEIGHT = SCREEN_WIDTH - 500

BOARD_WIDTH = SCREEN_HEIGHT - 300 # Leave space for UI elements
BOARD_HEIGHT = BOARD_WIDTH
SQUARE_SIZE = BOARD_WIDTH // 8
GAP_SQAURE =  SQUARE_SIZE * 0.05 # Gap between squares


# board
BOARD_X = 3 * SCREEN_WIDTH // 10 - BOARD_WIDTH // 2 
BOARD_Y = (SCREEN_HEIGHT - BOARD_HEIGHT) // 2
PIECE_SIZE = int(SQUARE_SIZE * 0.9)  # Leave some padding around pieces



# turn indicator
TURN_INDICATOR_RADIUS = 15
GAP_TURN_INDICATOR = 5
TURN_INDICATOR_X = BOARD_X + BOARD_WIDTH + TURN_INDICATOR_RADIUS + GAP_TURN_INDICATOR
TURN_INDICATOR_Y = BOARD_Y + TURN_INDICATOR_RADIUS


# promotion table
GAP_PROMOTION_TABLE = BOARD_HEIGHT // 15
PROMOTION_TABLE_Y = BOARD_Y + BOARD_HEIGHT + GAP_PROMOTION_TABLE
PROMOTION_TABLE_WIDTH = BOARD_WIDTH * 0.5
PROMOTION_TABLE_CELL_WIDTH = PROMOTION_TABLE_WIDTH // 4
PROMOTION_TABLE_CELL_HEIGHT = PROMOTION_TABLE_CELL_WIDTH
PROMOTION_TABLE_X = BOARD_X + (BOARD_WIDTH - PROMOTION_TABLE_WIDTH) // 2



# material table
MATERIAL_NUM = 10
# height of cell is same as width
MATERIAL_SCORE_WIDTH = SQUARE_SIZE * 0.5
MATERIAL_GAP = (BOARD_HEIGHT - MATERIAL_NUM * MATERIAL_SCORE_WIDTH) // (MATERIAL_NUM + 1)

MATERIAL_SCORE_X = BOARD_X - MATERIAL_SCORE_WIDTH - GAP_PROMOTION_TABLE
MATERIAL_SCORE_Y = BOARD_Y

MATERIAL_WHITE_PAWN_Y = MATERIAL_SCORE_Y + MATERIAL_GAP
MATERIAL_WHITE_KNIGHT_Y = MATERIAL_WHITE_PAWN_Y + MATERIAL_SCORE_WIDTH + MATERIAL_GAP
MATERIAL_WHITE_BISHOP_Y = MATERIAL_WHITE_KNIGHT_Y + MATERIAL_SCORE_WIDTH + MATERIAL_GAP
MATERIAL_WHITE_ROOK_Y = MATERIAL_WHITE_BISHOP_Y + MATERIAL_SCORE_WIDTH + MATERIAL_GAP
MATERIAL_WHITE_QUEEN_Y = MATERIAL_WHITE_ROOK_Y + MATERIAL_SCORE_WIDTH + MATERIAL_GAP
MATERIAL_BLACK_PAWN_Y = MATERIAL_WHITE_QUEEN_Y + MATERIAL_SCORE_WIDTH + MATERIAL_GAP
MATERIAL_BLACK_KNIGHT_Y = MATERIAL_BLACK_PAWN_Y + MATERIAL_SCORE_WIDTH + MATERIAL_GAP
MATERIAL_BLACK_BISHOP_Y = MATERIAL_BLACK_KNIGHT_Y + MATERIAL_SCORE_WIDTH + MATERIAL_GAP
MATERIAL_BLACK_ROOK_Y = MATERIAL_BLACK_BISHOP_Y + MATERIAL_SCORE_WIDTH + MATERIAL_GAP
MATERIAL_BLACK_QUEEN_Y = MATERIAL_BLACK_ROOK_Y + MATERIAL_SCORE_WIDTH + MATERIAL_GAP


GAP = SCREEN_WIDTH // 10 # gap between left and right side of the screen (board and info windows - time, pv and buttons)

# time info

TIME_INFO_X = BOARD_X + BOARD_WIDTH + GAP
TIME_INFO_Y = BOARD_Y
TIME_INFO_WIDTH = SCREEN_WIDTH - TIME_INFO_X - GAP
TIME_INFO_HEIGHT = 60
BLACK_TIME_INFO_X = TIME_INFO_X + TIME_INFO_WIDTH // 2
TIME_INFO_CELL_WIDTH = TIME_INFO_WIDTH // 2
