# screen
FPS = 60

SCREEN_WIDTH = 1500 # Extra space for UI elements
SCREEN_HEIGHT = SCREEN_WIDTH - 600

BOARD_WIDTH = SCREEN_HEIGHT - 300 # Leave space for UI elements
BOARD_HEIGHT = BOARD_WIDTH
SQUARE_SIZE = BOARD_WIDTH // 8
GAP_SQAURE =  SQUARE_SIZE * 0.05 # Gap between squares


# board
BOARD_X = 3 * SCREEN_WIDTH // 10 - BOARD_WIDTH // 2 
BOARD_Y = (SCREEN_HEIGHT - BOARD_HEIGHT) // 2
PIECE_SIZE = int(SQUARE_SIZE * 0.9)  # Leave some padding around pieces



# turn indicator
TURN_INDICATOR_RADIUS = 25
GAP_TURN_INDICATOR = SQUARE_SIZE // 2 + TURN_INDICATOR_RADIUS
TURN_INDICATOR_X = BOARD_X + BOARD_WIDTH + GAP_TURN_INDICATOR
TURN_INDICATOR_Y = BOARD_Y + TURN_INDICATOR_RADIUS


# promotion table
GAP_PROMOTION_TABLE = BOARD_HEIGHT // 15
PROMOTION_TABLE_Y = BOARD_Y + BOARD_HEIGHT + GAP_PROMOTION_TABLE
PROMOTION_TABLE_WIDTH = BOARD_WIDTH * 0.5
PROMOTION_TABLE_CELL_WIDTH = PROMOTION_TABLE_WIDTH // 4
PROMOTION_TABLE_CELL_HEIGHT = PROMOTION_TABLE_CELL_WIDTH
PROMOTION_TABLE_X = BOARD_X + (BOARD_WIDTH - PROMOTION_TABLE_WIDTH) // 2



# material table
MATERIAL_NUM = 10
# height of cell is same as width
MATERIAL_SCORE_WIDTH = SQUARE_SIZE * 0.5
MATERIAL_GAP = (BOARD_HEIGHT - MATERIAL_NUM * MATERIAL_SCORE_WIDTH) // (MATERIAL_NUM + 1)

MATERIAL_SCORE_X = BOARD_X - MATERIAL_SCORE_WIDTH - 2 * MATERIAL_GAP
MATERIAL_SCORE_Y = BOARD_Y

MATERIAL_WHITE_PAWN_Y = MATERIAL_SCORE_Y + MATERIAL_GAP
MATERIAL_WHITE_KNIGHT_Y = MATERIAL_WHITE_PAWN_Y + MATERIAL_SCORE_WIDTH + MATERIAL_GAP
MATERIAL_WHITE_BISHOP_Y = MATERIAL_WHITE_KNIGHT_Y + MATERIAL_SCORE_WIDTH + MATERIAL_GAP
MATERIAL_WHITE_ROOK_Y = MATERIAL_WHITE_BISHOP_Y + MATERIAL_SCORE_WIDTH + MATERIAL_GAP
MATERIAL_WHITE_QUEEN_Y = MATERIAL_WHITE_ROOK_Y + MATERIAL_SCORE_WIDTH + MATERIAL_GAP
MATERIAL_BLACK_PAWN_Y = MATERIAL_WHITE_QUEEN_Y + MATERIAL_SCORE_WIDTH + MATERIAL_GAP
MATERIAL_BLACK_KNIGHT_Y = MATERIAL_BLACK_PAWN_Y + MATERIAL_SCORE_WIDTH + MATERIAL_GAP
MATERIAL_BLACK_BISHOP_Y = MATERIAL_BLACK_KNIGHT_Y + MATERIAL_SCORE_WIDTH + MATERIAL_GAP
MATERIAL_BLACK_ROOK_Y = MATERIAL_BLACK_BISHOP_Y + MATERIAL_SCORE_WIDTH + MATERIAL_GAP
MATERIAL_BLACK_QUEEN_Y = MATERIAL_BLACK_ROOK_Y + MATERIAL_SCORE_WIDTH + MATERIAL_GAP


GAP = SCREEN_WIDTH // 15  # gap between left and right side of the screen (board and info windows - time, pv and buttons)

# time info
TIME_INFO_X = BOARD_X + BOARD_WIDTH + GAP
TIME_INFO_Y = BOARD_Y
TIME_INFO_WIDTH = SCREEN_WIDTH - TIME_INFO_X - GAP // 4
TIME_INFO_HEIGHT = 60
BLACK_TIME_INFO_X = TIME_INFO_X + TIME_INFO_WIDTH // 2
TIME_INFO_CELL_WIDTH = TIME_INFO_WIDTH // 2


# buttons
BUTTON_GAP = GAP // 4

CHANGE_SIDE_BUTTON_WIDTH = 5 * GAP // 4

PLAY_BUTTON_HEIGHT = 50
PLAY_BUTTON_X = BOARD_X + BOARD_WIDTH + GAP
PLAY_BUTTON_Y = BOARD_Y + BOARD_HEIGHT - PLAY_BUTTON_HEIGHT
PLAY_BUTTON_WIDTH = (TIME_INFO_WIDTH - 2 * BUTTON_GAP - CHANGE_SIDE_BUTTON_WIDTH) // 2


PAUSE_BUTTON_X = PLAY_BUTTON_X + PLAY_BUTTON_WIDTH + BUTTON_GAP
PAUSE_BUTTON_HEIGHT = PLAY_BUTTON_HEIGHT
PAUSE_BUTTON_Y = PLAY_BUTTON_Y
PAUSE_BUTTON_WIDTH = PLAY_BUTTON_WIDTH

CHANGE_SIDE_BUTTON_X = PLAY_BUTTON_X + PLAY_BUTTON_WIDTH + PAUSE_BUTTON_WIDTH + 2 * BUTTON_GAP
CHANGE_SIDE_BUTTON_HEIGHT = PLAY_BUTTON_HEIGHT
CHANGE_SIDE_BUTTON_Y = PLAY_BUTTON_Y


TIME_BUTTON_1_X = PLAY_BUTTON_X
TIME_BUTTON_1_HEIGHT = PLAY_BUTTON_HEIGHT
TIME_BUTTON_1_WIDTH = (TIME_INFO_WIDTH - 2 * BUTTON_GAP) // 3
TIME_BUTTON_1_Y = PLAY_BUTTON_Y + PLAY_BUTTON_HEIGHT + BUTTON_GAP

TIME_BUTTON_2_X = TIME_BUTTON_1_X + TIME_BUTTON_1_WIDTH + BUTTON_GAP
TIME_BUTTON_2_HEIGHT = TIME_BUTTON_1_HEIGHT
TIME_BUTTON_2_WIDTH = TIME_BUTTON_1_WIDTH
TIME_BUTTON_2_Y = PLAY_BUTTON_Y + PLAY_BUTTON_HEIGHT + BUTTON_GAP

TIME_BUTTON_3_X = TIME_BUTTON_1_X + TIME_BUTTON_1_WIDTH +  2 * BUTTON_GAP + TIME_BUTTON_2_WIDTH
TIME_BUTTON_3_HEIGHT = TIME_BUTTON_1_HEIGHT
TIME_BUTTON_3_WIDTH = TIME_BUTTON_1_WIDTH
TIME_BUTTON_3_Y = PLAY_BUTTON_Y + PLAY_BUTTON_HEIGHT + BUTTON_GAP

GAP_INFO = 10

# game status
GAME_STATUS_X = TIME_INFO_X
GAME_STATUS_WIDTH = TIME_INFO_WIDTH
GAME_STATUS_HEIGHT = TIME_INFO_HEIGHT // 3
GAME_STATUS_Y = TIME_INFO_Y + TIME_INFO_HEIGHT + GAP_INFO


# search info 
SEARCH_INFO_X = TIME_INFO_X
SEARCH_INFO_WIDTH = TIME_INFO_WIDTH
SEARCH_INFO_Y = GAME_STATUS_Y + GAME_STATUS_HEIGHT + GAP_INFO
SEARCH_INFO_HEIGHT = PLAY_BUTTON_Y - SEARCH_INFO_Y - 2 * GAP_INFO